### ISSUE TITLE
[Question] How to query using ST_* functions?

### ISSUE THREAD

**Issue by TerminalWitchcraft** [Boscop/diesel-geography#2]
I want to query the table and sort the result based on the distance from a given point. How can I achieve this using diesel-geometry?

**Comment by Boscop** [comment]
(Btw, this is diesel-geography, not diesel-geometry. But the queries for both are similar.)
You can `order by a <-> b` which will use a GIST index.
More info here:
https://gis.stackexchange.com/questions/136403/postgis-nearest-points-with-st-distance-knn
You can write raw string queries with `sql_query` or define a FFI for the ST_* functions you want to call, using https://docs.rs/diesel/1.4.2/diesel/macro.sql_function.html
If you write a FFI for some functions, I'd appreciate a PR so we can merge them into this crate :)

**Comment by dbrgn** [comment]
I tried to add support for the ST_DWithin function.

```rust
use diesel::sql_types::{Bool, Double, Nullable};
use diesel_geography::sql_types::Geography;
use diesel_geography::types::GeogPoint;

sql_function! {
    /// The postgis "ST_DWithin" function.
    fn st_dwithin(gg1: Nullable<Geography>, gg2: Nullable<Geography>, distance: Double) -> Bool;
}

...

let point = GeogPoint {
    x: lat,
    y: lon,
    srid: None,
};
let max_distance: f64 = 1000.0; // Meters
Location::belonging_to(user)
    .filter(st_dwithin(locations::geog, point, max_distance))
    .order(locations::name)
    .load(conn)
    .expect("Error loading locations")
```

However, like this I get an error message:

```
error[E0277]: the trait bound `diesel_geography::sql_types::Geography: diesel::query_builder::QueryId` is not satisfied
   --> src/data.rs:137:10
    |
137 |         .load(conn)
    |          ^^^^ the trait `diesel::query_builder::QueryId` is not implemented for `diesel_geography::sql_types::Geography`
    |
    = note: required because of the requirements on the impl of `diesel::query_builder::QueryId` for `diesel::sql_types::Nullable<diesel_geography::sql_types::Geography>`
```

Any ideas?

**Comment by Boscop** [comment]
I just merged your PR. Does the above work now? :)

**Comment by TerminalWitchcraft** [comment]
Thanks for merging the PR. I'll give it a try in few days.

**Comment by dbrgn** [comment]
> I just merged your PR. Does the above work now? :)

Sorry for the delayed response. I ended up writing a raw query in my case, but if I remember correctly the custom `sql_function` did work after the merge!

@TerminalWitchcraft maybe you can confirm.

**Comment by TerminalWitchcraft** [comment]
We ended up using a different Database. So I did not get a chance to test out the PR. However, assuming it's working as pointed out by @dbrgn , I'm closing the issue for now. Others can feel free to reopen if there are any other requirements.

Best,
Hitesh
